theme = "hermit-v2"
baseURL = 'https://joooi13.github.io/'
languageCode = 'en-us'
title = 'Yu Joi'

custom_css = ["custom_css/foo.css","custom_css/bar.css"]

[params]
  dateform        = "Jan 2, 2006"
  dateformShort   = "Jan 2"
  dateformNum     = "2006-01-02"
  dateformNumTime = "2006-01-02 15:04 -0700"

[[params.socialLinks]]
    name = "x"
    url = "https://twitter.com/"

[[params.socialLinks]]
    name = "github"
    url = "https://github.com/"
[[params.socialLinks]]
    name = "email"
    url = "https://github.com/"

[menu]

  [[menu.main]]
    name = "Posts"
    url = "posts/"
    weight = 10

  [[menu.main]]
    name = "About"
    url = "about/"
    weight = 20